# Generated by Django 5.2.8 on 2025-11-23 22:38

import django.db.models.deletion
import picklefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='saved_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField()),
                ('parameters', models.JSONField()),
                ('y_variable', models.TextField()),
                ('dropped_cols', models.JSONField(null=True)),
                ('random_state', models.IntegerField(null=True)),
                ('pickle_file', picklefield.fields.PickledObjectField(editable=False)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('file_trained_on', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processing.upload_file')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
