# Generated by Django 5.2.8 on 2025-11-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_saved_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_models',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='saved_models',
            name='model_class',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='saved_models',
            name='transformations',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='saved_models',
            name='y_predictions',
            field=models.JSONField(null=True),
        ),
    ]
