# Generated by Django 5.2.8 on 2025-12-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_saved_models_accuracy_saved_models_model_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_models',
            name='outliers',
            field=models.BooleanField(null=True),
        ),
    ]
