# Generated by Django 5.2.8 on 2025-12-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_user_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_models',
            name='guest',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='upload_file',
            name='guest',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user_images',
            name='guest',
            field=models.TextField(null=True),
        ),
    ]
