# Generated by Django 5.2.8 on 2026-02-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved_models',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='user_images',
            name='guest',
        ),
    ]
